### ISSUE TITLE
Apply Directive issues

### ISSUE THREAD

**Issue by Nevraeka** [RevillWeb/wc-styling-investigation#1]
Recently Apply mixins were moved to stage 0 and @tabatkins removed himself from the project. He is now working on [Shadow Parts spec](http://tabatkins.github.io/specs/css-shadow-parts/) which has `::part` & `::theme`(the potential equivalent to apply) . Id look into this instead but it will require a polyfill to be created 👎

**Comment by RevillWeb** [comment]
Thanks Erik this is useful info!

**Comment by Nevraeka** [comment]
Alternatively (until the Shadow Parts spec matures)- you could use postcss (with cssnext & webpack) to write apply mixins which then get turned into standard css in post compilation. Not optimal but something.

This might be a bad idea, in that the Apply spec is going away, but it is nice to get teams started on thinking about dynamic CSS

**Comment by Nevraeka** [comment]
The purpose of Shadow Parts is to not stuff CSS custom props with 'all-the-things' but have logic where is should be. As far as CSS custom properties go with browsers, IE11 is the only issue. Every other browser you support has full implementations and requires no fallback or polyfill. So...instead of an IE11 specific CSS file, what I have been doing is something like this (although I typically use a mixin in SASS to build this) 

```css
.some__class {
  color: #f00; /* for IE11 */
  color: var(--some-color); /* for other browsers */
}
```
The downside to this is no dynamic changes in IE11 so critical changes are hard coded for that experience.

The next step for me is to experiment with declaration of variables & scope...

```css
  :root {
    --some-var: #405;
  }

  .some__scoped_selector {
     color: var(--some-var);
  }

  .some__scoped_selector--active {
    --some-var: #555;
    color: var(--some-var);
  }
```
